#CC = gcc -ansi -pedantic -DDEBUG -g
CC = gcc

INSTALL = install

OBJS = loadconfig.o langcfg.o html.o dns.o tools.o main.o

compile: $(OBJS)
	$(CC) -o checkdns $(OBJS) -lresolv

install:
	cp checkdns /usr/local/bin/checkdns

clean:
	rm -f $(OBJS) checkdns

uninstall: clean
	rm /usr/local/bin/checkdns

all: compile install clean
